name: Deploy to FTP

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '19'

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Deploy to FTP
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./build/
                  server-dir: /

            - name: Send Telegram notification
              env:
                TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
                TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
              run: |
                LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
                curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ env.TELEGRAM_CHAT_ID }} -d text="https://tinyboohomecoming.com successfully updated! Commit: $LAST_COMMIT_MESSAGE"

            - name: Send Discord notification
              env:
                  DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1304151344726147163/D3xqlHDeDYBt2xgKeNrUn6qylgFmUn6QFg62s_gKe20XRJiVYK6oKKVWB4300NShkrg_
              run: |
                  LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
                  curl -s -X POST -H "Content-Type: application/json" \
                    -d "{\"content\": \"https://tinyboohomecoming.com successfully updated! Commit: $LAST_COMMIT_MESSAGE\"}" \
                    ${{ env.DISCORD_WEBHOOK_URL }}
